INSERT INTO USER (ID, NAME, BIRTH) VALUES (NULL, "小韩", '1993-5-1');
INSERT INTO USER (ID, NAME, BIRTH) VALUES (NULL, "小王", '1993-6-1');
INSERT INTO USER (ID, NAME, BIRTH) VALUES (NULL, "小李", '1993-7-1');
INSERT INTO USER (ID, NAME, BIRTH) VALUES (NULL, "小韩", '1993-8-1');
INSERT INTO USER (ID, NAME, BIRTH) VALUES (NULL, "小赵", '1993-9-1');
